// Code generated by entc, DO NOT EDIT.

package ent

import (
	"AppFactory/internal/data/ent/schema"
	"AppFactory/internal/data/ent/student"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	studentFields := schema.Student{}.Fields()
	_ = studentFields
	// studentDescExamNum is the schema descriptor for exam_num field.
	studentDescExamNum := studentFields[1].Descriptor()
	// student.ExamNumValidator is a validator for the "exam_num" field. It is called by the builders before save.
	student.ExamNumValidator = studentDescExamNum.Validators[0].(func(string) error)
	// studentDescChineseScore is the schema descriptor for chinese_score field.
	studentDescChineseScore := studentFields[4].Descriptor()
	// student.DefaultChineseScore holds the default value on creation for the chinese_score field.
	student.DefaultChineseScore = studentDescChineseScore.Default.(string)
	// studentDescMathScore is the schema descriptor for math_score field.
	studentDescMathScore := studentFields[5].Descriptor()
	// student.DefaultMathScore holds the default value on creation for the math_score field.
	student.DefaultMathScore = studentDescMathScore.Default.(string)
	// studentDescEnglishScore is the schema descriptor for english_score field.
	studentDescEnglishScore := studentFields[6].Descriptor()
	// student.DefaultEnglishScore holds the default value on creation for the english_score field.
	student.DefaultEnglishScore = studentDescEnglishScore.Default.(string)
	// studentDescTotalScore is the schema descriptor for total_score field.
	studentDescTotalScore := studentFields[7].Descriptor()
	// student.DefaultTotalScore holds the default value on creation for the total_score field.
	student.DefaultTotalScore = studentDescTotalScore.Default.(string)
	// studentDescClassRate is the schema descriptor for class_rate field.
	studentDescClassRate := studentFields[8].Descriptor()
	// student.DefaultClassRate holds the default value on creation for the class_rate field.
	student.DefaultClassRate = studentDescClassRate.Default.(string)
	// studentDescSchoolRate is the schema descriptor for school_rate field.
	studentDescSchoolRate := studentFields[9].Descriptor()
	// student.DefaultSchoolRate holds the default value on creation for the school_rate field.
	student.DefaultSchoolRate = studentDescSchoolRate.Default.(string)
	// studentDescStepRank is the schema descriptor for step_rank field.
	studentDescStepRank := studentFields[10].Descriptor()
	// student.DefaultStepRank holds the default value on creation for the step_rank field.
	student.DefaultStepRank = studentDescStepRank.Default.(string)
	// studentDescIsDeleted is the schema descriptor for is_deleted field.
	studentDescIsDeleted := studentFields[12].Descriptor()
	// student.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	student.DefaultIsDeleted = studentDescIsDeleted.Default.(string)
	// studentDescDeleteTime is the schema descriptor for delete_time field.
	studentDescDeleteTime := studentFields[13].Descriptor()
	// student.DefaultDeleteTime holds the default value on creation for the delete_time field.
	student.DefaultDeleteTime = studentDescDeleteTime.Default.(string)
}
