// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"AppFactory/internal/model/internal"
)

// QueryExamAll is the golang structure for table query_exam_all.
type QueryExamAll internal.QueryExamAll

// Fill with you ideas below.