// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"AppFactory/internal/model/internal"
)

// QueryExamMain is the golang structure for table query_exam_main.
type QueryExamMain internal.QueryExamMain

// Fill with you ideas below.