// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"AppFactory/internal/model/internal"

	"github.com/gogf/gf/net/ghttp"
)

// User is the golang structure for table t_user.
type User internal.User

// Fill with you ideas below.

const (
	// ContextKey 上下文变量存储键名
	ContextKey = "ContextKey"
)

// Context 请求上下文结构
type Context struct {
	Session *ghttp.Session // 当前Session管理对象
	User    *ContextUser   // 上下文用户信息
}

// ContextUser 请求上下文中的用户信息
type ContextUser struct {
	ID       uint64 // 用户ID
	Passport string // 用户账号
	Nickname string // 用户名称
}

type UserServiceSignUpReq struct {
	Passport string
	Nickname string
}
