// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table t_user.
type User struct {
    Id             uint64      `orm:"id,primary"       json:"id"`             //                          
    UserUuid       string      `orm:"user_uuid,unique" json:"userUuid"`       // 用户uuid                 
    UserName       string      `orm:"user_name"        json:"userName"`       // 用户名                   
    Password       string      `orm:"password"         json:"password"`       // 密码                     
    RealName       string      `orm:"real_name"        json:"realName"`       // 真实姓名                 
    Age            string      `orm:"age"              json:"age"`            // 年龄                     
    Sex            string      `orm:"sex"              json:"sex"`            // 1.男 2女                 
    Phone          string      `orm:"phone"            json:"phone"`          // 手机号                   
    Role           string      `orm:"role"             json:"role"`           // 1.学生 2.老师 3.管理员   
    Status         string      `orm:"status"           json:"status"`         // 1.启用 2禁用             
    ImagePath      string      `orm:"image_path"       json:"imagePath"`      // 头像地址                 
    LastActiveTime *gtime.Time `orm:"last_active_time" json:"lastActiveTime"` // 上一次活跃时间           
    IsDeleted      string      `orm:"is_deleted"       json:"isDeleted"`      // 是否删除 0不删除，1删除  
    CreatedAt      *gtime.Time `orm:"created_at"       json:"createdAt"`      //                          
    UpdatedAt      *gtime.Time `orm:"updated_at"       json:"updatedAt"`      //                          
}