// Code generated by protoc-gen-go-http. DO NOT EDIT.

package v1

import (
	context "context"
	http1 "github.com/go-kratos/kratos/v2/transport/http"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
// context./http.
const _ = http1.SupportPackageIsVersion1

type AppExcelHTTPServer interface {
	GetStudent(context.Context, *GetStudentRequest) (*GetStudentReply, error)

	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterAppExcelHTTPServer(s http1.ServiceRegistrar, srv AppExcelHTTPServer) {
	s.RegisterService(&_HTTP_AppExcel_serviceDesc, srv)
}

func _HTTP_AppExcel_SayHello_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error) (interface{}, error) {
	var in HelloRequest

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	out, err := srv.(AppExcelServer).SayHello(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_AppExcel_GetStudent_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error) (interface{}, error) {
	var in GetStudentRequest

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	out, err := srv.(AppExcelServer).GetStudent(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _HTTP_AppExcel_serviceDesc = http1.ServiceDesc{
	ServiceName: "api.webApp.v1.AppExcel",
	Methods: []http1.MethodDesc{

		{
			Path:    "/hello/{name}",
			Method:  "GET",
			Handler: _HTTP_AppExcel_SayHello_0,
		},

		{
			Path:    "/student/score_main",
			Method:  "POST",
			Handler: _HTTP_AppExcel_GetStudent_0,
		},
	},
	Metadata: "demo.proto",
}
