// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"AppFactory/internal/dao/internal"
)

// queryExamMainDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type queryExamMainDao struct {
	*internal.QueryExamMainDao
}

var (
	// QueryExamMain is globally public accessible object for table query_exam_main operations.
	QueryExamMain = &queryExamMainDao{
		internal.QueryExamMain,
	}
)

// Fill with you ideas below.