// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"AppFactory/internal/dao/internal"
)

// queryExamAllDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type queryExamAllDao struct {
	*internal.QueryExamAllDao
}

var (
	// QueryExamAll is globally public accessible object for table query_exam_all operations.
	QueryExamAll = &queryExamAllDao{
		internal.QueryExamAll,
	}
)

// Fill with you ideas below.