// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// QueryExamMainColumns holds the columns for the "query_exam_main" table.
	QueryExamMainColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "exam_num", Type: field.TypeString, Unique: true},
		{Name: "student_name", Type: field.TypeString},
		{Name: "class_name", Type: field.TypeString},
		{Name: "chinese_score", Type: field.TypeString, Default: "0"},
		{Name: "math_score", Type: field.TypeString, Default: "0"},
		{Name: "english_score", Type: field.TypeString, Default: "0"},
		{Name: "total_score", Type: field.TypeString, Default: "0"},
		{Name: "class_rate", Type: field.TypeString, Default: ""},
		{Name: "school_rate", Type: field.TypeString, Default: ""},
		{Name: "step_rank", Type: field.TypeString, Default: ""},
		{Name: "upload_date", Type: field.TypeString},
		{Name: "is_deleted", Type: field.TypeString, Default: "0"},
		{Name: "delete_time", Type: field.TypeString, Default: ""},
	}
	// QueryExamMainTable holds the schema information for the "query_exam_main" table.
	QueryExamMainTable = &schema.Table{
		Name:        "query_exam_main",
		Columns:     QueryExamMainColumns,
		PrimaryKey:  []*schema.Column{QueryExamMainColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		QueryExamMainTable,
	}
)

func init() {
	QueryExamMainTable.Annotation = &entsql.Annotation{
		Table: "query_exam_main",
	}
}
